---
# tasks for swarm deploy role

# - name: Create directory and change permissions
#   ansible.builtin.file:
#     path: /opt/docker/socks
#     mode: '0775'
#     state: directory
#     recurse: yes

# - name: Copy project docker-compose file
#   ansible.builtin.copy:
#     src: files/docker-compose.yml
#     dest: /opt/docker/socks/docker-compose.yml


# PROD

- name: Create project directory and change permissions
  ansible.builtin.file:
    path: /opt/docker/socks
    mode: '0775'
    state: directory
    recurse: yes

- name: Copy project docker-compose file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/yukht/ops_swarm/main/docker-compose.yml
    dest: /opt/docker/socks/docker-compose.yml
    mode: '0660'

- name: Docker deploy project to cluster
  ansible.builtin.shell: |
    cat docker-compose.yml | grep weaveworksdemos | awk '{print $2}' >> images.list && \
    for x in $(cat images.list); do docker pull $x; done && \
    docker stack deploy --with-registry-auth -c ./docker-compose.yml socks_stack && \
    docker service update --replicas=2 socks_stack_front-end
  args:
    executable: /bin/bash
    chdir: /opt/docker/socks
  register: deploy_output
 
- name: Print deploy result
  ansible.builtin.debug:
    var: deploy_output.stdout
    verbosity: 2

